### ISSUE TITLE
 When MCP23017  binding is installed on Openhabian 1.3 (with OH 2.1), Openhab cannot start. 

### ISSUE THREAD

**Issue by szymic1** [openhab/openhab1-addons#5237]
When MCP23017  binding is installed on  Openhaian 1.3 (with OH 2.1), OH cannot start. 

## Expected Behavior
OH shoud start when I put MCP23017 binding jar in /usr/share/openhab2/addons. 

## Current Behavior
I've tried to install MCP23017 binding (from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3). 
but when I copied this to adds directory there are problem with starting Openhab.
In the openhablog there are following information. "Started dashboard.." is displayed every 10seconds (in a loop):

```
2017-07-02 12:48:31.703 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:48:31.720 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
2017-07-02 12:48:46.125 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.items'
2017-07-02 12:48:54.990 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'test.rules'
2017-07-02 12:49:44.305 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.10:8080
2017-07-02 12:49:44.322 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.10:8443
```
It happens when system start but it also happen when OH running and I put MCP file on runnnign system. This binding works on OH 2.0 without problem.

## Possible Solution
Only uninstalling MCP binding helps.

## Steps to Reproduce (for bugs)
1. Install Openhabian 1.3 from SD image 
2.Copy  MCP binding file to  /usr/share/openhab2/addons ( download binding from https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.mcp23017/target/3 I've used org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar	 but 1.10 also does not work)

## Your Environment
Raspberry 2, Openhabian 1.3, with Razberry hut

**Comment by 9037568** [comment]
Since you indicated this binding works in OH 2.0, but fails in OH 2.1, the problem likely lies in ESH, because the binding hasn't changed.

Try opening this issue in the [ESH issue tracker](http://github.com/eclipse/smarthome/issues).

**Comment by szymic1** [comment]
To be honest I do not know where is problem. I wonder if the old binding need not be modified to work with the new OH - I do not know. I create issue for OH and make a link to this.

**Comment by szymic1** [comment]
Task related to smarthome and openhab-cor was closed @kaikreuzer suggests that is problem of addson.

**Comment by 9037568** [comment]
I just merged Kai's fix. Can you try again with the latest snapshot jar next time it gets built? (ie. with a build after 1491)

**Comment by kaikreuzer** [comment]
Build is through: https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1492/

**Comment by szymic1** [comment]
To test this fix should I upgrade my OH to the newest snapshot or we are talking about newe version of binding file (https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1492/org.openhab.binding$org.openhab.binding.mcp23017/)

**Comment by szymic1** [comment]
I've installed the newest version of MCP binding, nothing changed problem still exists.

**Comment by 9037568** [comment]
I tried this.  Since I'm not running on a Raspberry Pi, I get the new error:

````
20:32:14.678 [ERROR] [ng.mcp23017.internal.MCP23017Binding] - MCP23017 Binding needs to be run a Raspberry Pi - deactivating it here.
````

If @szymic1 can submit a debug log, we might be able to debug further.

**Comment by kaikreuzer** [comment]
@9037568 This message is normal - I added it through my PR to signal to the user that the binding won't work as expected. Nonetheless, it does not crash anymore, but further in the log you will see that it starts its services and that the bundle is active as expected (without causing any restarts of the dashboard).

**Comment by szymic1** [comment]
When I've put new version of MCP binding I've got loop (the same situation as before). 
Log with level DEBUG can be found here:
https://drive.google.com/open?id=0B68VuZDaIVt5MlZJSFlfSzk1c2s

My reproduction steps:
1) installation of Openhabian 1.3
2) copying MCP binding to addson directory

```
2017-07-13 22:44:52.303 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-07-13 22:44:53.385 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-07-13 22:48:11.423 [INFO ] [b.core.service.AbstractActiveService] - mcp23017 Refresh Service has been started
2017-07-13 22:49:26.644 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2017-07-13 22:49:36.416 [INFO ] [assic.internal.servlet.WebAppServlet] - Stopped Classic UI
2017-07-13 22:49:36.535 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Stopped HABmin servlet
2017-07-13 22:49:37.185 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2017-07-13 22:49:37.216 [INFO ] [panel.internal.HABPanelDashboardTile] - Stopped HABPanel
2017-07-13 22:49:37.239 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2017-07-13 22:51:08.109 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.6:8080
2017-07-13 22:51:08.129 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.6:8443
2017-07-13 22:52:22.825 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.6:8080
2017-07-13 22:52:22.843 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.6:8443
2017-07-13 22:53:16.788 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.6:8080
2017-07-13 22:53:16.808 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.6:8443
2017-07-13 22:54:04.344 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.6:8080
2017-07-13 22:54:04.361 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.6:8443
2017-07-13 22:54:52.950 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.6:8080

```

**Comment by 9037568** [comment]
@kaikreuzer - yes, I was aware of that, but thanks for pointing it out.

**Comment by 9037568** [comment]
Thanks, @szymic1.

Please turn on DEBUG logging for the org.openhab.ui.dashboard and org.openhab.binding.MCP23017 packages and recapture. I don't see any ERRORs in the log, which I would've thought would be occurring to produce the looping restarts...

These lines are interesting, but more detail is needed:

````
2017-07-14 08:37:47.319 [INFO ] [org.apache.felix.fileinstall        ] - Installing bundle org.openhab.binding.mcp23017 / 1.11.0.201707130521
...
2017-07-14 08:37:47.464 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.mcp23017 (208): Starting destruction process
2017-07-14 08:37:47.464 [DEBUG] [org.eclipse.jetty.jmx.ObjectMBean   ] - Method Cache: dump()
2017-07-14 08:37:47.466 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.mcp23017 (208): Not an extended bundle or destruction of extension already finished
...
2017-07-14 08:37:48.365 [DEBUG] [mpl.info.InfoBundleTrackerCustomizer] - Ignore incorrect info null provided by bundle org.openhab.binding.mcp23017

````

**Comment by 9037568** [comment]
Oh, also, please show your configurations (items/rules/sitemap). What bindings do you have installed?

**Comment by szymic1** [comment]
only MCP. Installing MCP binding was a first step after finishing Openhabian installation.

**Comment by szymic1** [comment]
Today I've made first test on Rpi 3 and it seems that problems does not exist on Rp3. Reproduction steps where tha same - installing Openhabian 1.3 and after installing MCP binding. Today I  repeat once again tests.

**Comment by szymic1** [comment]
I've made once again test on Rp3 and it also exist on this platform :(

**Comment by szymic1** [comment]
>the karaf console eject the session, 

In my test Karaf consolre restart every few seconds  but also  all  UI interfaces cannot start.

**Comment by 9037568** [comment]
In that case, @szymic1 I hope that you can provide a full debug log.

**Comment by szymic1** [comment]
Log is the same as for Rp2 (few post above)
https://drive.google.com/open?id=0B68VuZDaIVt5MlZJSFlfSzk1c2s

**Comment by 9037568** [comment]
The log file, I'm afraid, doesn't give much useful info.

It looks like the OH system is starting over and over again. I count 5 loops in this log. But there are no errors flagged, and I can't see a reason why OH would be restarting.

Have you checked the Pi's system logs for clues?

You could also try inquiring in the [community forum](http://community.openhab.org) for clues on why the DashboardService is repeatedly restarting.

**Comment by 9037568** [comment]
Oh, one other thing you should check. The status of the binding in the karaf console.

````
bundle:list | grep mcp
bundle:status <bundleId>
````

**Comment by szymic1** [comment]
I try to check but I have to reinstall OH once again after installation of MCP I cannot login to Karaf console (and I alos cannot switch on DEBUG mode).

**Comment by NickolayGerasimenko** [comment]
have the same issue with fresh raspbian release
![image](https://user-images.githubusercontent.com/807345/28481044-fbbd0fb0-6e6b-11e7-8c66-0332ec8e545b.png)

**Comment by NickolayGerasimenko** [comment]
Kernel downgrade I described here solved the issue:

### sudo rpi-update 52241088c1da59a359110d39c1875cda56496764

https://community.openhab.org/t/how-to-install-mcp23017-binding-with-jar-file/29348/25?u=stnick

**Comment by 9037568** [comment]
The post from @NickolayGerasimenko does not describe the same problem as originally reported in this thread.

**Comment by phili007** [comment]
Have downgrade kernel form 4.9.35 to 4.4.50 and it works perfect with MCP23017, same configuration, don't change anything at the configuration. MCP hast Problem with 4.9.x

Step's :
sudo rpi-update 52241088c1da59a359110d39c1875cda56496764
reboot 
connect Karaf:
> 188 | Resolved |  80 | 2.2.0.201707190537     | openHAB 1.x Compatibility Layer
195 | Resolved |  80 | 1.11.0.201707160110    | openHAB GPIO Binding
196 | Resolved |  80 | 1.11.0.201707160110    | openHAB GPIO IO Module
197 | Resolved |  80 | 1.11.0.201707160110    | openHAB mcp23017 Binding

remove org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar file from add-on folder
wait sort time
copy  org.openhab.binding.mcp23017-1.11.0-SNAPSHOT.jar file to add-on Folder
connect karaf:
> 188 | Active   |  80 | 2.2.0.201707190537     | openHAB 1.x Compatibility Layer
195 | Active   |  80 | 1.11.0.201707160110    | openHAB GPIO Binding
196 | Active   |  80 | 1.11.0.201707160110    | openHAB GPIO IO Module
198 | Active   |  80 | 1.11.0.201707160110    | openHAB mcp23017 Binding

logout karaf
sudo /etc/init.d/openhab2 restart
alle MCP23017 works with this kernel 👍

**Comment by falkena** [comment]
Hi everybody,

i integrated and rebuild MCP* bindings against current Pi4J snapshot. This should solve openHAB start issues (https://www.raspberrypi.org/forums/viewtopic.php?t=182191#p1156722). Jar’s can be found here: https://github.com/falkena/binaries

Can somebody else test, please? If it works, i’ll open PR with fix.

Thanks and kind regards,

Alexander

**Comment by szmolnar** [comment]
Alexander,
I tried your fox without luck, MCB binding is not loaded.

My system is a Rpi3 with DebianSketch (4.9.41-v7+), running OH2.1.0.

**Comment by szmolnar** [comment]
phili007,

Thanks for the solution, it's working!

**Comment by hr3** [comment]
Hello falkena,
I have the same problem with #1034 (Kernel = Linux 4.9.35-v7+)
